### ISSUE TITLE
Ошибка при тестировании 

### ISSUE THREAD

**Issue by goro22052** [perlestius/Zabbix_Templates#1]
Ошибка при тестировании 

zabbix_get -s kyv-s-f02 -p  10050 -k "dfsr.params"
C:\Scripts\Get-DFSRObjectParam.ps1 : ? 㤠???? ?ਢ易?? ???㬥?? ? ??ࠬ???? "Object", ⠪ ??? ?? ?।?⠢???? ᮡ?? 
?????? ??ப?.
    + CategoryInfo          : InvalidData: (:) [Get-DFSRObjectParam.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-DFSRObjectParam.ps1
root@zabbix:/home/appliance#

**Comment by perlestius** [comment]
Какую метрику хотите получить? Судя по выводу, не хватает параметра на входе.
