### ISSUE TITLE
Issue Importing XML (zabbix 5.0) - Cannot find Value Map

### ISSUE THREAD

**Issue by almoreau** [perlestius/Zabbix_Templates#2]
Hi!
I'm very interested in your plugin, but when I import the xml template, I have the following issue : 
Cannot find value map "DFSR::ServiceState" used for item "DFS Replication service state" on "Template App DFS Replication".

Do you have an idea why i do have this error? The value maps are well included in the file...

**Comment by almoreau** [comment]
Found the solution! 
You have to be admin to create value map!

**Comment by perlestius** [comment]
Good! I hope, the template will help you to monitor DFSR.
Feel free to ask your questions here.
Also, please, write your feedback on [Zabbix Share](https://share.zabbix.com/operating-systems/windows/dfs-replication-for-zabbix-2-2-and-above)
