### ISSUE TITLE
Value of type "string" is not suitable for value type "Numeric (unsigned)". Value ""

### ISSUE THREAD

**Issue by doumhfr** [perlestius/Zabbix_Templates#3]
Hi,

i'm trying to use your template.

environment :
Zabbix 5.2, Zabbix Agent 2

I have imported the template, created a dfsr.conf file with userparameter in zabbix_agent2.conf.d folder, copied the two ps1 script on the servers
I have created an active directory account, set it administrator on the servers, and change the agent service account with this one.

But in Zabbix I've got this error on all items.

Value of type "string" is not suitable for value type "Numeric (unsigned)". Value ""

I have run the script manually without problems :  

PS C:\Users\zabbixserviceaccount> C:\Progra~1\Zabbix~1\Scripts\DFSR\Get-DFSRObjectParam.ps1 Log WarnCount 1h
183

(with agent2 you can't have space on the path, it's for that I use short path)

I have no idea what I'm missing

**Comment by perlestius** [comment]
Hi!
Please, show me info from agent log.

**Comment by doumhfr** [comment]
this for example ? 

2021/02/20 18:53:50.920581 received passive check request: 'dfsr.params[ServiceUptime]' from 'xx.xx.xx.xx'
2021/02/20 18:53:50.920581 [1] processing update request (1 requests)
2021/02/20 18:53:50.920581 [1] adding new request for key: 'dfsr.params[ServiceUptime]'
2021/02/20 18:53:50.920581 [1] created direct exporter task for plugin 'UserParameter' itemid:0 key 'dfsr.params[ServiceUptime]'
2021/02/20 18:53:50.920581 executing direct exporter task for key 'dfsr.params[ServiceUptime]'
2021/02/20 18:53:50.920581 [UserParameter] executing command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Progra~1\Zabbix~1\Scripts\DFSR\Get-DFSRObjectParam.ps1 "ServiceUptime" "$2" "$3"'
2021/02/20 18:53:51.001582 plugin Cpu: executing collector task
2021/02/20 18:53:51.001582 plugin WindowsPerfMon: executing collector task
2021/02/20 18:53:51.001582 executing exporter task for itemid:499371 key 'service.info["lmhosts",state]'
2021/02/20 18:53:51.001582 executed exporter task for itemid:499371 key 'service.info["lmhosts",state]'
2021/02/20 18:53:51.447580 [UserParameter] command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Progra~1\Zabbix~1\Scripts\DFSR\Get-DFSRObjectParam.ps1 "ServiceUptime" "$2" "$3"' length:0 output:''
2021/02/20 18:53:51.447580 executed direct exporter task for key 'dfsr.params[ServiceUptime]'
2021/02/20 18:53:51.447580 sending passive check response: '' to 'xx.xx.xx.xx'

Looks like the result from the script is empty

I'm currently logged in with the service account that run Zabbixagent, I start powershell as admin, I run tghe script without problem 

PS C:\Windows\system32> powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Progra~1\Zabbix~1\Scripts\DFSR\Get-DFSRObjectParam.ps1 "ServiceUptime" "$2" "$3"
159056.1607163

**Comment by perlestius** [comment]
And what is timeout parameter's value in agent config?

**Comment by doumhfr** [comment]
maximum, 30s

**Comment by perlestius** [comment]
I've tested the template with Zabbix 5.0.0 server and Win2019 host with agent2 x64 v5.0.8.2400 for you. It works fine in my lab environment.

> (with agent2 you can't have space on the path, it's for that I use short path)

Khm... Why do you think so? Is it official limitation? I use these settings in my agent2 config and it works fine:
`UserParameter=dfsr.discovery[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\Get-DFSRObjectDiscovery.ps1" "$1"`
`UserParameter=dfsr.params[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\Get-DFSRObjectParam.ps1" "$1" "$2" "$3"`

I think. it's something wrong with paths to your PS1-scripts. Try to put them to C:\Scripts\ folder, update your agent config accordingly and restart agent service.
Also, please, ask 2 questions:
1) What OS run on your monitored host?
2) Do you use x64 or x86 version of agent2?

**Comment by doumhfr** [comment]
for the script path, I had problem using previously a template to monitor MSSQL
impossible to have it working unless I change the path to short name to avoid space

searching for the problem I found this https://www.zabbix.com/forum/zabbix-help/410155-agent2-userparameter-for-powershell-with-quotes-in-file-paramter (it was the error message I had)
now I don't have error so for me the path to the script is ok

and found this too https://github.com/golang/go/issues/17149

OS is 2012 R2. Agent is x64 version

**Comment by perlestius** [comment]
>searching for the problem I found this

questionable decision... I think. the proper solution is not to use environment variable **%ProgramFiles%** in agent config and use explicit path **C:\Program Files** instead.

Did you try to move PS1 scripts to C:\Scripts folder?

**Comment by doumhfr** [comment]
Yes, exactly the same 

2021/02/20 21:35:12.526046 [UserParameter] command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\Get-DFSRObjectParam.ps1 "ServiceUptime" "$2" "$3"' length:0 output:''

**Comment by perlestius** [comment]
Show me these strings from your agent config file:
`UserParameter=dfsr.discovery[*],powershell ...`
`UserParameter=dfsr.params[*],powershell ...`

**Comment by doumhfr** [comment]
```
UserParameter=dfsr.discovery[*],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\Get-DFSRObjectDiscovery.ps1 "$1"
UserParameter=dfsr.params[*],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\Get-DFSRObjectParam.ps1 "$1" "$2" "$3"
```

**Comment by perlestius** [comment]
Try this (add quotes to paths):
UserParameter=dfsr.discovery[*],powershell.exe -NoProfile -ExecutionPolicy Bypass -File **"**C:\Scripts\DFSR\Get-DFSRObjectDiscovery.ps1**"** "$1"
UserParameter=dfsr.params[*],powershell.exe -NoProfile -ExecutionPolicy Bypass -File **"**C:\Scripts\DFSR\Get-DFSRObjectParam.ps1**"** "$1" "$2" "$3"

**Comment by doumhfr** [comment]
`2021/02/20 22:09:02.233386 [1] adding new request for key: 'dfsr.params[ServiceUptime]'
2021/02/20 22:09:02.233386 [1] created direct exporter task for plugin 'UserParameter' itemid:0 key 'dfsr.params[ServiceUptime]'
2021/02/20 22:09:02.233386 executing direct exporter task for key 'dfsr.params[ServiceUptime]'
2021/02/20 22:09:02.233386 [UserParameter] executing command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Scripts\DFSR\Get-DFSRObjectParam.ps1" "ServiceUptime" "$2" "$3"'
2021/02/20 22:09:02.284386 [UserParameter] command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Scripts\DFSR\Get-DFSRObjectParam.ps1" "ServiceUptime" "$2" "$3"' length:245 output:'Processing -File '"C'
2021/02/20 22:09:02.284386 executed direct exporter task for key 'dfsr.params[ServiceUptime]'
2021/02/20 22:09:02.284386 sending passive check response: 'Processing -File '"C:\Scripts\DFSR\Get-DFSRObjectParam.ps1"' failed: Illegal characters in path. Specify a valid path for the -File parameter.
Windows PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.' to 'xx.xx.xx.xx'`

it doesn't work, it's exactly for that I have remove space in path, and use old short path name instead.
I had this error previously when I try to monitor SQL Server 

For me it's not a problem of path and conf
the script is executed. What is strange is, if I run the script manually I have the value, If I run the script with userparameter and zabbix agent, the script return no value

**Comment by perlestius** [comment]
I understand.
Is your Windows up to date?
Show me **$PSVersionTable** output from powershell console. It will be something like this:
PSVersion                      5.1.17763.1007                                                                               
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17763.1007                                                                              
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1

**Comment by doumhfr** [comment]
`Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.34014
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`

yes it is

**Comment by perlestius** [comment]
Try to rename **Get-DFSRObjectParam.ps1** and **Get-DFSRObjectDiscovery.ps1** to **01.ps1** and **02.ps1** accordingly and made the same changes in agent config.

**Comment by doumhfr** [comment]
PS C:\Program Files\Zabbix Agent 2> .\zabbix_agent2.exe -t dfsr.params[ServiceUptime] -c .\zabbix_agent2.conf
dfsr.params[ServiceUptime]                    [s|]

sorry I don't understand why you want to rename the file but no change with another name ;)

**Comment by perlestius** [comment]
> sorry I don't understand why you want to rename the file but no change with another name ;)

There was an error "Illegal characters in path" in your agent log. I don't know which symbol PowerShell considers illegal, so, we set the most simple names for the files.

Please, try to add parameters' names:
UserParameter=dfsr.discovery[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\02.ps1 -ObjectType "$1"
UserParameter=dfsr.params[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\01.ps1 -Object "$1" -Param1 "$2" -Param2 "$3"

Also, you can try [this](https://rcmtech.wordpress.com/2013/08/23/powershell-and-double-quotes-on-the-command-line/)

**Comment by doumhfr** [comment]
no there is not ;)
the illegal charaters in path appears when you asked me to add double quote for the path in the agent configuration 

But now I don't have the error. The script is executed
the only problem is that when the script is run by the agent, it always return nothing

**Comment by perlestius** [comment]
Did you try to add parameters' names?
UserParameter=dfsr.discovery[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\Get-DFSRObjectDiscovery.ps1 **-ObjectType** "$1"
UserParameter=dfsr.params[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\Get-DFSRObjectParam.ps1 **-Object** "$1" **-Param1** "$2" **-Param2** "$3"
And did you try [this link](https://rcmtech.wordpress.com/2013/08/23/powershell-and-double-quotes-on-the-command-line/)?

**Comment by doumhfr** [comment]
Just try, same thing with parameters names

for the link, not sure to understand what you want me to try

For information I have verify on the mssql script and conf, it's set exactly like you
UserParameter=database.mssql.status[*],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\MSSQL\Discovery.mssql.databasestatus.ps1 -instName "$1" -dbName "$2"

and it's working (same agent version, only difference is OS, Win2016 in this case)

**Comment by perlestius** [comment]
>for the link, not sure to understand what you want me to try

I want you to try replace double quotes with single quotes and other symbols for parameters. Something like this:
[variant 1]
UserParameter=dfsr.params[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\01.ps1 -Object '$1' -Param1 '$2' -Param2 '$3'

[variant 2]
UserParameter=dfsr.params[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\01.ps1 -Object \"$1\" -Param1 \"$2\" -Param2 \"$3\"

UserParameter=dfsr.params[],powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Scripts\DFSR\01.ps1 -Object """$1""" -Param1 """$2""" -Param2 """$3"""

>and it's working (same agent version, only difference is OS, Win2016 in this case)

Another OS is a big difference in your case. It seems, PowerShell in your Win2012 R2 behaves strange with quotes. I've tested my template with operating systems from from 2008R2 to 2019 and there were no problems.

**Comment by doumhfr** [comment]
I have just put your scripts on the same 2016 server : 

PS C:\Program Files\Zabbix Agent 2>  .\zabbix_agent2.exe -t dfsr.params[RoleInstalled] -c .\zabbix_agent2.conf
dfsr.params[RoleInstalled]                    [s|]
PS C:\Program Files\Zabbix Agent 2> .\zabbix_agent2.exe -t databases.mssql.discovery -c .\zabbix_agent2.conf
databases.mssql.discovery                     [s|{
    "data":  [
                 {
                     "{#SQLINSTANCENAME}":  "MSSQLSERVER",
                     "{#DBNAME}":  "master",
                     "{#SQLINSTANCE}":  "SQLServer"
                 },

mssql userparameter work well, dfsr not.

**Comment by perlestius** [comment]
The same for me:
![image](https://user-images.githubusercontent.com/46634660/108610772-5d033e80-73e9-11eb-96c3-0e6c2e4771a9.png)

Did you add UserParameters for DFSR to zabbix_agent2.conf on Win2016 and restart agent service after that?

**Comment by doumhfr** [comment]
yes 

It's something crazy.

Just made a test
I have added a out-file in the script to also write the value in a file.

running manually file is created
running with zabbix agent, no.

but the script is executed : 
![image](https://user-images.githubusercontent.com/16317462/108611035-c0d23b00-73da-11eb-9189-e7995ecb7097.png)

(the escape before the double quote in the command line are ok, I have the same for the mssql monitoring)

**Comment by doumhfr** [comment]
I have added a start-transcript to see : 

launched via zabbix agent : 

```
SerializationVersion: 1.1.0.1
**********************
**********************
Windows PowerShell transcript end
End time: 20210221003452
**********************
```


launched manually : 

```
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is c:\temp\dfs.log
False
**********************
Windows PowerShell transcript end
End time: 20210221003538
**********************
```


I don't understand why we don't have the FALSE in the file, but ok, but more than that, how it is possible that in the transcript, we have the line Windows Powershell transcript end, but not the line Transcript started !!!!

**Comment by doumhfr** [comment]
Ok don't want to know why, because I have exactly the same "$1" in the MSSQL monitoring config,but I have removed the " " on the config files and now DFSR monitoring is working....

really strange that we don't have the same behavior, but thanks a lot for your help
Maybe I can try with single quotes are """ if you want

**Comment by perlestius** [comment]
Khm. Very interesting. Can you give me your zabbix_agent2.exe and sql PS1 script files, please. I want to do some tests.

**Comment by perlestius** [comment]
I created small test for our case.
1. Extract files from [this archive](https://github.com/perlestius/Zabbix_Templates/files/6017652/AgentTest.zip) to C:\AgentTest\ folder
2. Run C:\AgentTest\agent-test.cmd and show me the output
3. Replace c:\AgentTest\zabbix_agent2.exe with your file zabbix_agent2.exe, run C:\AgentTest\agent-test.cmd and show me the output.

**Comment by doumhfr** [comment]
your agent2.exe :

C:\AgentTest>zabbix_agent2.exe -t test.paramquotes["My Input Parameter"] -c "C:\
AgentTest\zabbix_agent2.win.conf"
test.paramquotes[My Input Parameter]          [s|Input parameter is My Input Par
ameter]

my agent 2 (5.2.0 on this server) : 

C:\AgentTest>zabbix_agent2.exe -t test.paramquotes["My Input Parameter"] -c "C:\
AgentTest\zabbix_agent2.win.conf"
test.paramquotes[My Input Parameter]          [s|C:\AgentTest\Test-ParamValue.ps
1 : A positional parameter cannot be found that
accepts argument 'Input'.
    + CategoryInfo          : InvalidArgument: (:) [Test-ParamValue.ps1], Pare
   ntContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Test-ParamValue.ps1]

**Comment by perlestius** [comment]
I downloaded the last agent2 version at this moment from official Zabbix site.
It seems, your agent2 version have trouble with double quotes.
Removing quotes from config file is not a good solution: as a result, the script will not be able to process parameters with spaces and you cannot get some metrics. It's not a problem for my DFSR scripts, because they receive parameters without spaces, but probably you will get problems in the future.
So, I recommend you to update your agent and use quotes in your agent config. Also, you will be able to set normal path to Zabbix agent folder instead of using short-path workaround.

**Comment by doumhfr** [comment]
exact

just test on another server with the last version and no problem !
I will update the agent version thanks
